name: integration tests
on:
  workflow_dispatch:
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      plantbookdb:
        # Docker Hub image
        image: ghcr.io/proplants/plantbook/database:latest
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-v1-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-v1-go-
      - name: Test
        run: go test --tags=integration  ./...
        env:
          DB_HOST_PORT: localhost:5432
